export const ADD_TUTORIAL = 'ADD_TUTORIAL';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const SELECT_TUTORIAL = 'SELECT_TUTORIAL';

export const UPDATE_USER = 'UPDATE_USER';
export const SET_SERVER_SIDE_ERRORS = 'SET_SERVER_SIDE_ERRORS';
export const SYNC_DATA = 'SYNC_DATA';
export const SORT_TUTORIALS = 'SORT_TUTORIALS';
export const SET_REQUESTING = 'SET_REQUESTING';
export const SET_PREVIEWING = 'SET_PREVIEWING';
export const SET_NAVIGATING = 'SET_NAVIGATING';
export const SET_PENDING_STEP_INDEX = 'SET_PENDING_STEP_INDEX';

export const SET_ACTIVE = 'SET_ACTIVE';
export const RESET_STATE = 'RESET_STATE';
export const SET_ALL_FETCHED = 'SET_ALL_FETCHED';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';

export const TUTORIAL_REPOSITORY_READY = 'TUTORIAL_REPOSITORY_READY';

export const SET_TASK_ID = 'SET_TASK_ID';
