export const SET_USER = 'SET_USER';
export const SET_ACTIVE = 'SET_ACTIVE';
export const RESET_STATE = 'RESET_STATE';

export const SET_ALL_FETCHED = 'SET_ALL_FETCHED';
export const SET_REQUESTING = 'SET_REQUESTING';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';

export const LIST_TUTORIALS = 'LIST_TUTORIALS';
export const ADD_TUTORIAL = 'ADD_TUTORIAL';
// export const SELECT_TUTORIAL = 'SELECT_TUTORIAL';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
